<?php

namespace Database\Seeders;

use App\Services\DashboardService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContratoSeeder extends Seeder
{
    public function run(): void
    {
        $conn = DB::connection('tenant');

        $fornecedores = $conn->table('fornecedores')->pluck('id', 'cnpj')->toArray();
        $secretarias  = $conn->table('secretarias')->pluck('id', 'sigla')->toArray();
        $servidores   = $conn->table('servidores')->pluck('id', 'matricula')->toArray();

        if (empty($fornecedores) || empty($secretarias)) {
            return;
        }

        $contratos = [
            // ── Contratos VIGENTES (variados) ─────────────────────────
            [
                'numero'                 => '001/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Prestação de serviços de limpeza e conservação predial para a Secretaria de Administração',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['55.666.777/0001-29'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0009'] ?? null,
                'data_inicio'            => '2026-01-01',
                'data_fim'               => '2026-12-31',
                'data_assinatura'        => '2025-12-20',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 480000.00,
                'valor_mensal'           => 40000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.012345',
                'fundamento_legal'       => 'Art. 28, I da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'limpeza',
                'score_risco'            => 20,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 16.67,
                'fonte_recurso'          => 'Recurso Próprio',
                'dotacao_orcamentaria'   => '04.122.0001.2001.3.3.90.37',
            ],
            [
                'numero'                 => '002/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Aquisição de equipamentos de informática para modernização do parque tecnológico municipal',
                'tipo'                   => 'compra',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['11.222.333/0001-81'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0004'] ?? null,
                'data_inicio'            => '2026-02-01',
                'data_fim'               => '2026-08-01',
                'data_assinatura'        => '2026-01-25',
                'prazo_meses'            => 6,
                'prorrogacao_automatica' => false,
                'valor_global'           => 1500000.00,
                'tipo_pagamento'         => 'parcelado',
                'numero_processo'        => '2025.023456',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'tecnologia',
                'score_risco'            => 40,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 0,
                'fonte_recurso'          => 'Recurso Próprio',
                'dotacao_orcamentaria'   => '04.126.0002.1001.4.4.90.52',
            ],
            [
                'numero'                 => '003/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Reforma e adequação do prédio da Secretaria de Saúde — Unidade Central',
                'tipo'                   => 'obra',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'concorrencia',
                'fornecedor_id'          => $fornecedores['22.333.444/0001-40'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMS'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0001'] ?? null,
                'data_inicio'            => '2026-01-15',
                'data_fim'               => '2028-01-14',
                'data_assinatura'        => '2026-01-10',
                'prazo_meses'            => 24,
                'prorrogacao_automatica' => false,
                'valor_global'           => 2800000.00,
                'tipo_pagamento'         => 'por_medicao',
                'numero_processo'        => '2025.034567',
                'responsavel_tecnico'    => 'Eng. Carlos Alberto Silva — CREA 12345/MT',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'obras',
                'score_risco'            => 30,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 15.50,
                'fonte_recurso'          => 'Emenda Parlamentar + Recurso Próprio',
                'dotacao_orcamentaria'   => '10.302.0010.1005.4.4.90.51',
            ],
            [
                'numero'                 => '005/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Contratação de serviços de assessoria jurídica especializada em licitações',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'inexigibilidade',
                'fornecedor_id'          => $fornecedores['10.222.333/0001-24'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0004'] ?? null,
                'data_inicio'            => '2026-01-10',
                'data_fim'               => '2027-01-09',
                'data_assinatura'        => '2026-01-05',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 240000.00,
                'valor_mensal'           => 20000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.067890',
                'fundamento_legal'       => 'Art. 74, III da Lei 14.133/2021',
                'categoria'              => 'nao_essencial',
                'score_risco'            => 10,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 0,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '006/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Fornecimento de merenda escolar — alimentação para 45 escolas municipais',
                'tipo'                   => 'compra',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['88.999.111/0001-06'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SME'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0003'] ?? null,
                'data_inicio'            => '2026-02-03',
                'data_fim'               => '2027-02-02',
                'data_assinatura'        => '2026-01-28',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 3600000.00,
                'valor_mensal'           => 300000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.078901',
                'fundamento_legal'       => 'Art. 28, I da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'alimentacao',
                'score_risco'            => 55,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 8.33,
                'fonte_recurso'          => 'PNAE + Recurso Próprio',
                'dotacao_orcamentaria'   => '12.306.0012.2015.3.3.90.30',
            ],
            [
                'numero'                 => '007/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Prestação de serviços de vigilância armada e desarmada para prédios municipais',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['99.111.222/0001-65'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMSP'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0013'] ?? null,
                'data_inicio'            => '2026-01-01',
                'data_fim'               => '2027-12-31',
                'data_assinatura'        => '2025-12-18',
                'prazo_meses'            => 24,
                'prorrogacao_automatica' => true,
                'valor_global'           => 1920000.00,
                'valor_mensal'           => 80000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.089012',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'seguranca',
                'score_risco'            => 25,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 8.33,
                'fonte_recurso'          => 'Recurso Próprio',
                'dotacao_orcamentaria'   => '06.181.0006.2008.3.3.90.37',
            ],
            [
                'numero'                 => '008/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Manutenção preventiva e corretiva de elevadores nos prédios públicos municipais',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'dispensa',
                'fornecedor_id'          => $fornecedores['77.888.999/0001-47'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0009'] ?? null,
                'data_inicio'            => '2026-01-15',
                'data_fim'               => '2027-01-14',
                'data_assinatura'        => '2026-01-10',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 96000.00,
                'valor_mensal'           => 8000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2026.001234',
                'fundamento_legal'       => 'Art. 75, II da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'manutencao',
                'score_risco'            => 15,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 8.33,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '009/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Locação de veículos para transporte de servidores e materiais — frota administrativa',
                'tipo'                   => 'locacao',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['20.333.444/0001-83'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMTM'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0015'] ?? null,
                'data_inicio'            => '2026-01-20',
                'data_fim'               => '2027-01-19',
                'data_assinatura'        => '2026-01-15',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 720000.00,
                'valor_mensal'           => 60000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.098765',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'transporte',
                'score_risco'            => 35,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 8.33,
                'fonte_recurso'          => 'Recurso Próprio',
                'dotacao_orcamentaria'   => '26.122.0026.2030.3.3.90.33',
            ],
            [
                'numero'                 => '010/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Aquisição de medicamentos e insumos hospitalares para UPAs e postos de saúde',
                'tipo'                   => 'compra',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'adesao_ata',
                'fornecedor_id'          => $fornecedores['33.444.555/0001-09'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMS'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0006'] ?? null,
                'data_inicio'            => '2026-02-01',
                'data_fim'               => '2027-01-31',
                'data_assinatura'        => '2026-01-28',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 4500000.00,
                'tipo_pagamento'         => 'parcelado',
                'numero_processo'        => '2026.002345',
                'fundamento_legal'       => 'Art. 86 da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'saude',
                'score_risco'            => 65,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 5.00,
                'fonte_recurso'          => 'SUS + Recurso Próprio',
                'dotacao_orcamentaria'   => '10.303.0010.2012.3.3.90.30',
            ],
            [
                'numero'                 => '011/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Construção de quadra poliesportiva coberta — Bairro CPA III',
                'tipo'                   => 'obra',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'concorrencia',
                'fornecedor_id'          => $fornecedores['22.333.444/0001-40'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SME'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0007'] ?? null,
                'data_inicio'            => '2026-02-10',
                'data_fim'               => '2026-12-10',
                'data_assinatura'        => '2026-02-05',
                'prazo_meses'            => 10,
                'prorrogacao_automatica' => false,
                'valor_global'           => 850000.00,
                'tipo_pagamento'         => 'por_medicao',
                'numero_processo'        => '2025.045678',
                'responsavel_tecnico'    => 'Eng. Patricia Lima — CREA 67890/MT',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'obras',
                'score_risco'            => 45,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 3.00,
                'fonte_recurso'          => 'Emenda Parlamentar',
                'dotacao_orcamentaria'   => '27.812.0027.1010.4.4.90.51',
            ],
            [
                'numero'                 => '012/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Serviços de manutenção elétrica e hidráulica predial em 28 unidades municipais',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['30.444.555/0001-42'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMO'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0008'] ?? null,
                'data_inicio'            => '2026-02-15',
                'data_fim'               => '2027-02-14',
                'data_assinatura'        => '2026-02-10',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 360000.00,
                'valor_mensal'           => 30000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.056789',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'manutencao',
                'score_risco'            => 20,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 0,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '013/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Contratação de sistema integrado de gestão ambiental — licenciamento eletrônico',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['11.222.333/0001-81'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0010'] ?? null,
                'data_inicio'            => '2026-02-01',
                'data_fim'               => '2027-01-31',
                'data_assinatura'        => '2026-01-25',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 180000.00,
                'valor_mensal'           => 15000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.067891',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'tecnologia',
                'score_risco'            => 15,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 8.33,
                'fonte_recurso'          => 'Recurso Próprio',
            ],

            // ── Contratos VENCIDOS ─────────────────────────────────────
            [
                'numero'                 => '004/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Locação de veículos para transporte escolar — rota urbana',
                'tipo'                   => 'locacao',
                'status'                 => 'vencido',
                'modalidade_contratacao' => 'pregao_presencial',
                'fornecedor_id'          => $fornecedores['20.333.444/0001-83'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SME'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0003'] ?? null,
                'data_inicio'            => '2025-02-01',
                'data_fim'               => '2025-12-20',
                'data_assinatura'        => '2025-01-25',
                'prazo_meses'            => 10,
                'prorrogacao_automatica' => false,
                'valor_global'           => 360000.00,
                'valor_mensal'           => 36000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2024.056789',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'transporte',
                'score_risco'            => 60,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 100.00,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '014/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Fornecimento de material de escritório e expediente para todas as secretarias',
                'tipo'                   => 'compra',
                'status'                 => 'vencido',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['44.555.666/0001-60'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMA'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0009'] ?? null,
                'data_inicio'            => '2025-01-01',
                'data_fim'               => '2025-12-31',
                'data_assinatura'        => '2024-12-20',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 150000.00,
                'tipo_pagamento'         => 'parcelado',
                'numero_processo'        => '2024.078901',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'outros',
                'score_risco'            => 10,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 100.00,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '015/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Serviços de coleta de resíduos sólidos de saúde em unidades hospitalares',
                'tipo'                   => 'servico',
                'status'                 => 'vencido',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['55.666.777/0001-29'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMS'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0001'] ?? null,
                'data_inicio'            => '2025-03-01',
                'data_fim'               => '2026-02-28',
                'data_assinatura'        => '2025-02-20',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 420000.00,
                'valor_mensal'           => 35000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2024.089012',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'saude',
                'score_risco'            => 70,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 100.00,
                'fonte_recurso'          => 'SUS',
            ],

            // ── Contrato SUSPENSO ──────────────────────────────────────
            [
                'numero'                 => '016/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Construção de ponte sobre o Rio Coxipó — ligação bairro Pedra 90',
                'tipo'                   => 'obra',
                'status'                 => 'suspenso',
                'modalidade_contratacao' => 'concorrencia',
                'fornecedor_id'          => $fornecedores['22.333.444/0001-40'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMO'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0005'] ?? null,
                'data_inicio'            => '2025-06-01',
                'data_fim'               => '2027-05-31',
                'data_assinatura'        => '2025-05-20',
                'prazo_meses'            => 24,
                'prorrogacao_automatica' => false,
                'valor_global'           => 8500000.00,
                'tipo_pagamento'         => 'por_medicao',
                'numero_processo'        => '2024.112233',
                'responsavel_tecnico'    => 'Eng. Fernando Pires — CREA 54321/MT',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'obras',
                'score_risco'            => 85,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 22.00,
                'observacoes'            => 'Suspenso por decisão judicial — Ação Civil Pública nº 0001234-56.2025',
                'fonte_recurso'          => 'Convênio Federal + Recurso Próprio',
                'dotacao_orcamentaria'   => '15.451.0015.1003.4.4.90.51',
            ],

            // ── Contrato CANCELADO ─────────────────────────────────────
            [
                'numero'                 => '017/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Serviço de recape asfáltico em vias urbanas do Distrito Sul',
                'tipo'                   => 'obra',
                'status'                 => 'cancelado',
                'modalidade_contratacao' => 'tomada_preco',
                'fornecedor_id'          => $fornecedores['77.888.999/0001-47'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMO'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0008'] ?? null,
                'data_inicio'            => '2025-04-01',
                'data_fim'               => '2025-10-01',
                'data_assinatura'        => '2025-03-25',
                'prazo_meses'            => 6,
                'prorrogacao_automatica' => false,
                'valor_global'           => 1200000.00,
                'tipo_pagamento'         => 'por_medicao',
                'numero_processo'        => '2024.223344',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'obras',
                'score_risco'            => 90,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 12.00,
                'observacoes'            => 'Cancelado por irregularidade na execução — Parecer Jurídico nº 456/2025',
                'fonte_recurso'          => 'Recurso Próprio',
            ],

            // ── Contrato ENCERRADO ─────────────────────────────────────
            [
                'numero'                 => '018/2024',
                'ano'                    => '2024',
                'objeto'                 => 'Serviços de consultoria para implantação do Portal de Transparência Municipal',
                'tipo'                   => 'servico',
                'status'                 => 'encerrado',
                'modalidade_contratacao' => 'inexigibilidade',
                'fornecedor_id'          => $fornecedores['10.222.333/0001-24'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMF'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0011'] ?? null,
                'data_inicio'            => '2024-06-01',
                'data_fim'               => '2025-05-31',
                'data_assinatura'        => '2024-05-25',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 320000.00,
                'tipo_pagamento'         => 'parcelado',
                'numero_processo'        => '2024.334455',
                'fundamento_legal'       => 'Art. 74, III da Lei 14.133/2021',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'tecnologia',
                'score_risco'            => 5,
                'nivel_risco'            => 'baixo',
                'percentual_executado'   => 100.00,
                'fonte_recurso'          => 'Recurso Próprio',
            ],

            // ── Contratos com VENCIMENTO PRÓXIMO (para alertas) ────────
            [
                'numero'                 => '019/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Serviço de impressão e reprografia para a rede municipal de ensino',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_eletronico',
                'fornecedor_id'          => $fornecedores['44.555.666/0001-60'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SME'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0007'] ?? null,
                'data_inicio'            => '2025-04-01',
                'data_fim'               => '2026-03-31',
                'data_assinatura'        => '2025-03-25',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => false,
                'valor_global'           => 144000.00,
                'valor_mensal'           => 12000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2024.445566',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'outros',
                'score_risco'            => 50,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 83.33,
                'fonte_recurso'          => 'Recurso Próprio',
            ],
            [
                'numero'                 => '020/2025',
                'ano'                    => '2025',
                'objeto'                 => 'Contratação de empresa para organização de eventos culturais — Calendário 2025/2026',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'pregao_presencial',
                'fornecedor_id'          => $fornecedores['10.222.333/0001-24'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMCT'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0014'] ?? null,
                'data_inicio'            => '2025-07-01',
                'data_fim'               => '2026-04-30',
                'data_assinatura'        => '2025-06-20',
                'prazo_meses'            => 10,
                'prorrogacao_automatica' => false,
                'valor_global'           => 280000.00,
                'tipo_pagamento'         => 'por_medicao',
                'numero_processo'        => '2025.112233',
                'categoria'              => 'nao_essencial',
                'categoria_servico'      => 'educacao',
                'score_risco'            => 30,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 70.00,
                'fonte_recurso'          => 'Recurso Próprio + Lei Aldir Blanc',
            ],

            // ── Contrato de VALOR ALTO (para destaque no dashboard) ────
            [
                'numero'                 => '021/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Gestão e operação do sistema de transporte coletivo municipal — linhas urbanas',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'concorrencia',
                'fornecedor_id'          => $fornecedores['66.777.888/0001-88'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMTM'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0015'] ?? null,
                'data_inicio'            => '2026-01-01',
                'data_fim'               => '2030-12-31',
                'data_assinatura'        => '2025-12-15',
                'prazo_meses'            => 60,
                'prorrogacao_automatica' => false,
                'valor_global'           => 45000000.00,
                'valor_mensal'           => 750000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.998877',
                'fundamento_legal'       => 'Art. 28, I da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'transporte',
                'score_risco'            => 70,
                'nivel_risco'            => 'alto',
                'percentual_executado'   => 3.33,
                'fonte_recurso'          => 'Tarifa + Subsídio Municipal',
                'dotacao_orcamentaria'   => '26.453.0026.2035.3.3.90.39',
            ],

            // ── Contrato de Assistência Social ─────────────────────────
            [
                'numero'                 => '022/2026',
                'ano'                    => '2026',
                'objeto'                 => 'Serviço de acolhimento institucional para crianças e adolescentes em situação de risco',
                'tipo'                   => 'servico',
                'status'                 => 'vigente',
                'modalidade_contratacao' => 'dispensa',
                'fornecedor_id'          => $fornecedores['10.222.333/0001-24'] ?? reset($fornecedores),
                'secretaria_id'          => $secretarias['SMAS'] ?? reset($secretarias),
                'servidor_id'            => $servidores['MAT-0012'] ?? null,
                'data_inicio'            => '2026-01-01',
                'data_fim'               => '2026-12-31',
                'data_assinatura'        => '2025-12-22',
                'prazo_meses'            => 12,
                'prorrogacao_automatica' => true,
                'valor_global'           => 960000.00,
                'valor_mensal'           => 80000.00,
                'tipo_pagamento'         => 'mensal',
                'numero_processo'        => '2025.887766',
                'fundamento_legal'       => 'Art. 75, VIII da Lei 14.133/2021',
                'categoria'              => 'essencial',
                'categoria_servico'      => 'outros',
                'score_risco'            => 40,
                'nivel_risco'            => 'medio',
                'percentual_executado'   => 16.67,
                'fonte_recurso'          => 'FNAS + Recurso Próprio',
                'dotacao_orcamentaria'   => '08.243.0008.2010.3.3.90.39',
            ],
        ];

        foreach ($contratos as $contrato) {
            $existing = $conn->table('contratos')
                ->where('numero', $contrato['numero'])
                ->exists();

            if (! $existing) {
                $contratoId = $conn->table('contratos')->insertGetId(
                    array_merge($contrato, [
                        'classificacao_sigilo' => 'publico',
                        'publicado_portal'     => true,
                        'created_at'           => now(),
                        'updated_at'           => now(),
                    ])
                );

                // Cria fiscal titular para contratos vigentes
                if ($contrato['status'] === 'vigente') {
                    $conn->table('fiscais')->insert([
                        'contrato_id'  => $contratoId,
                        'servidor_id'  => $contrato['servidor_id'],
                        'nome'         => $this->getNomeFiscal($contrato['numero']),
                        'matricula'    => 'FISC-' . str_pad($contratoId, 4, '0', STR_PAD_LEFT),
                        'cargo'        => 'Fiscal de Contrato',
                        'email'        => 'fiscal' . $contratoId . '@prefeitura.gov.br',
                        'data_inicio'  => $contrato['data_inicio'],
                        'is_atual'     => true,
                        'tipo_fiscal'  => 'titular',
                        'created_at'   => now(),
                        'updated_at'   => now(),
                    ]);
                }
            }
        }

        // Agrega dados do dashboard para refletir os contratos inseridos
        try {
            app(DashboardService::class)->agregar();
        } catch (\Throwable) {
            // Silencia erro caso a tabela dashboard_agregados ainda não exista
        }
    }

    private function getNomeFiscal(string $numero): string
    {
        $nomes = [
            '001/2026' => 'Juliana Carvalho Freitas',
            '002/2026' => 'Roberto José Ferreira',
            '003/2026' => 'Ana Paula Ribeiro da Silva',
            '005/2026' => 'Carlos Eduardo Mendes',
            '006/2026' => 'Maria Aparecida Santos',
            '007/2026' => 'Thiago Henrique Sousa',
            '008/2026' => 'Juliana Carvalho Freitas',
            '009/2026' => 'Rafael Moreira da Costa',
            '010/2026' => 'Renata Cristina Almeida',
            '011/2026' => 'Lucas Fernando Barbosa',
            '012/2026' => 'Fernando Augusto Pires',
            '013/2026' => 'Gustavo Henrique Nascimento',
            '019/2025' => 'Lucas Fernando Barbosa',
            '020/2025' => 'Isabela Cristina Duarte',
            '021/2026' => 'Rafael Moreira da Costa',
            '022/2026' => 'Camila Rodrigues Martins',
        ];

        return $nomes[$numero] ?? 'Maria Aparecida Santos';
    }
}
